name: PlantUML Action
description: GitHub Action for drawing UML diagrams with PlantUML
inputs:
  puml_version:
    description: PlantUML software version
    default: "latest"
    required: true
  py2puml_version:
    description: py2puml python package version
    default: "latest"
    required: true
  path:
    description: the filepath to the domain following the py2puml definition
    required: true
  module:
    description: the module name of the domain following the py2puml definition
    required: true
  output_dir:
    description: the directory where the PNG should be saved to. File names default to the module name, but differ by file extension (.puml/.png).
    default: diagrams
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.puml_version }}
    - ${{ inputs.py2puml_version }}
    - ${{ inputs.path }}
    - ${{ inputs.module }}
    - ${{ inputs.output_dir }}
branding:
  color: green
  icon: code
