name: PlantUML Action
description: GitHub Action for drawing UML diagrams with PlantUML
inputs:
  version:
    description: PlantUML software version
    required: false
  path:
    description: the filepath to the domain following the py2puml definition
    required: true
  module:
    description: the module name of the domain following the py2puml definition
    required: true
  png_output_path:
    description: the filepath to the output PNG
    default: class_diagram.png
    required: false
  puml_output_path:
    description: the filepath to the output PUML
    default: class_diagram.puml
    required: false
runs:
  using: docker
  image: Dockerfile
branding:
  color: green
  icon: code
