name: Test PlantUML-E2E-Action
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  shellcheck:
    name: Analyze shell scripts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
  generate_diagram:
    name: Generate PlantUML diagram
    needs: [shellcheck]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build & render diagram
        uses: ./
        with:
          puml_version: "latest"
          pip_install_deps_cmd: "pip install -r tests/requirements.txt"
          path: "tests"
          module: "tests"
          output_dir: "diagrams"
