name: Test PlantUML-E2E-Action
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  shellcheck:
    name: Analyze shell scripts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run shellcheck
        run: bash -c 'shopt -s globstar nullglob; shellcheck **/*.sh'
  process:
    name: Process PlantUML diagram
    needs: [shellcheck]
    runs-on: ubuntu-latest
    env:
        MODULE: "tests"
        OUTPUT_DIR: "diagrams"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build & render diagram
        uses: ./
        with:
          puml_version: "latest"
          py2puml_version: "latest"
          path: "tests"
          module: ${{ env.MODULE }}
          output_dir: ${{ env.OUTPUT_DIR }}
      - name: Display diagram
        run: |
          cat ${{ env.OUTPUT_DIR }}/${{ env.MODULE }}.png
