name: Test PlantUML Action
on: [push, pull_request]

jobs:
  shellcheck:
    name: Analyze shell scripts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run shellcheck
        run: bash -c 'shopt -s globstar nullglob; shellcheck **/*.sh'
  process:
    name: Process PlantUML diagram
    runs-on: ubuntu-latest
    env:
      PUML_OUTPUT_PATH: test_diagram.puml
      PNG_OUTPUT_PATH: test_diagram.png
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build & render diagram
        uses: ./
        with:
          args: "test_diagram.puml tests tests"
      - name: Display diagram
        run: cat test_diagram.png
